# Задание 1
Написать SimpleModel другим способом. Использовать model = nn.Sequential() https://pytorch.org/tutorials/beginner/nn_tutorial.html?highlight=mnist ". + hw.pdf ( https://github.com/d-pack/LessonsPAK/blob/main/s14/hw.pdf )

In [52]:
import numpy as np
import torch
import torch.nn as nn
import pandas as pd
from scipy.signal import convolve2d

In [57]:
def matrix_conv(m1: list, m2: list):
    a, b = len(m1), len(m1[0])  
    c, d = len(m2), len(m2[0])
    res = [[0]*(b-d+1) for i in range(a-c+1)]
    for i in range(a-c+1):
        for j in range(b-d+1):
            tmp2 = 0
            for u in range(c):
                tmp1 = 0
                for v in range(d):
                    tmp1 += m1[i+u][j+v] * m2[u][v]
                tmp2 += tmp1
            res[i][j] = tmp2
    return res

In [53]:
#1_1
in_ch = 64
out_ch = 10

model = nn.Sequential(
    nn.Linear(in_ch, 32),
    nn.ReLU(),
    nn.Linear(32, out_ch, bias=False),
    nn.ReLU(),
)

In [60]:
#2_1
rgb = torch.tensor([[[1,2,1],[2,4,2],[1,2,1]], #цветное изображение
                       [[-1,0,1],[0,0,0],[1,0,-1]],
                       [[0,1,0],[1,2,1],[0,1,0]]],
                      dtype=torch.float32)

weig = torch.tensor([[[1,0],[0,1]], #ядро
                       [[0,-1],[-1,0]],
                       [[1,-1],[0,0]]],
                      dtype=torch.float32)
print("------------------------------------------")

answ = []
i = 0
for i in range (3):
    answ += [matrix_conv(rgb[i], weig[i])] #складываем rgb

print (np.array(answ))

------------------------------------------
[[[ 5.  4.]
  [ 4.  5.]]

 [[ 0. -1.]
  [-1.  0.]]

 [[-1.  1.]
  [-1.  1.]]]


In [12]:
#2_2
class Layer:
    def __init__(self,in_channels, out_channels, kernel_size,padding,stride,dilation):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.padding = padding
        self.stride = stride
        self.dilation = dilation

    def rec_field(lays):
        stris = 1
        r = 1
        for i in lays:
            stris *= i.stride
            r += i.dilation * (i.kernel_size - 1) * stris
        return r

layers = [Layer(1,1,7,3,1,1),Layer(1,1,3,1,2,1),Layer(1,1,2,0,2,1),Layer(1,1,3,100500,1,2),Layer(1,1,3,28,3,1)]


Layer.rec_field(layers)

55

In [13]:
#2_3
pic3 = torch.empty((1,224,224)) #входное изображение
model3 = nn.Sequential(
    nn.Conv2d(in_channels=1, out_channels=1, kernel_size=7, stride=2, padding=3),
    nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=1),
    nn.MaxPool2d(2, padding=0, stride=2),
    nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, dilation=3),
)
answ = model3(pic3).shape #узнаём размер
print(answ)

torch.Size([1, 26, 26])
