In [102]:
import numpy as np

from collections import Counter

a = np.array([3,14,3,2,14,5,5,5,5,3,43,2,2])
print(a)
b=Counter(a).most_common()
print(b) #частота + сортировка
c = list({b[i][0]: b[i][1] for i in range(0, len(b), 1)}.keys())
print(c)

[ 3 14  3  2 14  5  5  5  5  3 43  2  2]
[(5, 4), (3, 3), (2, 3), (14, 2), (43, 1)]
[5, 3, 2, 14, 43]


In [210]:
import numpy as np
h, w = 100, 200
picture = np.random.randint(0, 256, (h, w, 3), dtype=np.uint8)
#print(picture)
to_2dim = np.split(np.ravel(picture, order='C'), h*w) 
uniqueA = np.unique(to_2dim, axis = 0)
print(len(uniqueA))

19991


In [29]:
import numpy as np

def moving_avg(arr, n):
        x = np.array(arr)
        sq = np.cumsum(np.insert(x, 0, 0)) 
        return (sq[n:] - sq[:-n]) / n


Z = [15,26,37,48,59,34,2,5,67,2,234,5]
print(moving_avg(Z,3))

[ 26.          37.          48.          47.          31.66666667
  13.66666667  24.66666667  24.66666667 101.          80.33333333]


In [1]:
import numpy as np

def check(a):
    if a[0] + a[1] > a[2] and a[0] + a[2] > a[1] and a[1] + a[2] > a[0]:
        return a

e = np.array([[7,10,12],
   [1,2,3],
   [4,3,6],
   [3,4,8]])
print(e)
sq = list(map(check, e))
print (sq)

[[ 7 10 12]
 [ 1  2  3]
 [ 4  3  6]
 [ 3  4  8]]
[array([ 7, 10, 12]), None, array([4, 3, 6]), None]
